### ISSUE TITLE
Ubuntu menu item not showing on arm64

### ISSUE THREAD

**Issue by MarcDoughty** [netbootxyz/netboot.xyz#1004]
**Describe the bug**
Using latest release, Ubuntu installations are not showing up in the menus under arm64.

**To Reproduce**
1. Grab a Raspberry Pi, install an EFI implementation ( e.g.,https://github.com/pftf/RPi4 ) and boot to an arm64 build of netboot.xyz.
2. Ubuntu not rendering on menus alongside CentOS, Debian, etc.

**Expected behavior**
Ubuntu arm64 installation options.

**Additional context**
It looks like other distros with arm64 were recently reworked in the menus, but Ubuntu was left out?

**Comment by antonym** [comment]
Yeah, Ubuntu still needs a bit of rework since arm distros do not reside on releases.ubuntu.com but reside on https://cdimage.ubuntu.com/releases/20.04.3/release/ instead.

I just need to work around those upstream inconsistencies in the menu and build a netboot release for it. I'll try and get to it this weekend and then I'll enable it on the arm64 menu if it all works out.

**Comment by antonym** [comment]
Found that I was having issues with Legacy network installs on arm64, but 20.04 and up Subiquity works.  You should be able to give it a try from the Development Endpoint menu under Utilities.
