### ISSUE TITLE
Arch Linux 2021.12.01 - No such file or directory

### ISSUE THREAD

**Issue by seiuneko** [netbootxyz/netboot.xyz#1057]
![2021-12-06_22-31](https://user-images.githubusercontent.com/25706824/144864371-0df6ecb1-a3a0-4bcd-a8b6-44c76d967f58.png)
https://boot.netboot.xyz/ipxe/netboot.xyz.lkrn

**Comment by antonym** [comment]
If you go into the iPXE shell, can you do a echo `${arch}` and let me know what you get? It sounds like it's not identifying the arch or it's beyond the scope of the two checks:

```
iseq ${os_arch} x86_64 && set os_arch x86_64 ||
iseq ${os_arch} i386 && set os_arch i686 ||
```

The ${os_arch} is the part probably not getting set after /boot.

**Comment by seiuneko** [comment]
![2021-12-07_14-53](https://user-images.githubusercontent.com/25706824/144981076-4436d9e5-273f-4d57-a526-7b3e87231f55.png)

**Comment by antonym** [comment]
Make sure you are on the latest version of the menus and ipxe image. I refactored the arch stuff a few months ago.  I tested with latest tonight and could not reproduce.

**Comment by seiuneko** [comment]
It is already the latest version. 
![2021-12-07_15-28](https://user-images.githubusercontent.com/25706824/144985293-35d5a500-b79f-49f8-a249-1832f607e14b.png)

**Comment by null-dev** [comment]
I'm having the same issue.

I believe the issue is caused by using a static IP. It causes this `goto` to be invoked: https://github.com/netbootxyz/netboot.xyz/blob/7ffd805cb70fac148873442d11bf11e13dd27bd4/roles/netbootxyz/templates/menu/archlinux.ipxe.j2#L6 which then causes this line to be skipped: https://github.com/netbootxyz/netboot.xyz/blob/7ffd805cb70fac148873442d11bf11e13dd27bd4/roles/netbootxyz/templates/menu/archlinux.ipxe.j2#L8

Introduced in this commit: https://github.com/netbootxyz/netboot.xyz/commit/179ec5c6145e29fb46ec08a4f593ad66dd0cc0c6

**EDIT:** Actually, just ended up creating a PR to fix this: https://github.com/netbootxyz/netboot.xyz/pull/1072
