### ISSUE TITLE
Ubuntu live images fail to boot

### ISSUE THREAD

**Issue by danboid** [netbootxyz/netboot.xyz#1125]
I have set up a local instance of the latest netboot.xyz docker container Ubuntu 22.04 but I am unable to successfully boot any of the Ubuntu 22.04 and 20.04 live images. After netboot has downloaded one of the several Ubuntu live images, it seems to drop to BusyBox and I get the errors:

```
curl: (23) Failed writing body (0 != 1378)
Done.
Unable to find a live file system on the network
```

I am able to boot the normal Ubuntu install image from Netboot.xyz fine.

**Comment by danboid** [comment]
ATM (inc. in my PR) the path for the assets is marked as optional when really it should be stated as required else it breaks this feature which is one of the main advantages of setting up your own netboot server.

**Comment by borekon** [comment]
I tried several distros, and many of them won't boot with the same message

**Comment by antonym** [comment]
I wasn't getting this error with 8GB of RAM but once I switched it to 4GB, I begin getting a similar error.

```
curl: (23) Failed writing body (0 != 14216)
done.
Unable to find a live file system on the network.
```

I was testing with locally synced assets. The Live CDs are generally fatter and have to load more into memory. There may be some ramdisk_size settings that could be tuned but I would suggest feeding it more RAM and see what the result is.

Generally if you want to keep a lower memory footprint, the Linux Menu installers are generally the way to go, even though the Ubuntu network installer is now fatter than it used to be because it pulls the ISO down during boot. 

If you want to load the full Live CD from the second menu, typically all of those will require more RAM. If it fails in the `initrd` section, more than likely it's either having a problem getting on the network or runs out of space when retrieving the rootfs.

**Comment by docseymour12-hash** [comment]
Fix this pls
