### ISSUE TITLE
DBAN does not boot up from netboot.xyz hosted

### ISSUE THREAD

**Issue by ChrisThePCGeek** [netbootxyz/netboot.xyz#1415]
[X]: This bug persists when memory is increased beyond 8GB.

**Describe the bug**

**To Reproduce**
1. boot via ipxe usb drive image
2. select DBAN from menu options
3. first option for a quick wipe all disks

**Expected behavior**

error message "cat: can't open /proc/cmdline : no such file or directory"
**Screenshots**

**Additional context**

**Comment by ChrisThePCGeek** [comment]
Update on this I get the same issue with the docker container self hosted version of nb-xyz

**Comment by Firminator** [comment]
DBAN is dead for a number of years. The FOSS successor was NHellFire's DBAN fork and these days it's ShredOS. All three are based on nwipe so they are all very similar. ShredOS has the most recent wiping code and better hardware support than DBAN (think RAID controllers in servers for example). Last I checked ShredOS was in the netboot menu but I'm not sure if the version is current. If it's not you can try these instructions for PXE booting ShredOS: https://github.com/PartialVolume/shredos.x86_64/discussions/148

I'd leave DBAN in the menu but mark it as stale or dead for users.

**Comment by ChrisThePCGeek** [comment]
Hey thanks thats very helpful and great to know, I had no idea.  It really should just be removed like you said if its deprecated for sure.  What's funny is it worked when I tried to net boot it in a vm on my proxmox server but not on a bare metal machine. oh well. I'm glad there is a better alternative and I will def look into that

**Comment by antonym** [comment]
I didn't run into the issue on DBAN when I ran it, but as @Firminator pointed out, it is pretty old and unmaintained as it was acquired by a company and then development ended on it. I may pull down DBAN because it also is limited to Legacy menu and not UEFI. Users are just more familiar with DBAN to do wiping. ShredOS is what I recommend for disk wiping. I also just gave it a bump to the most current. 

Their tagging is a bit complex for the bot that checks tags so I'll need to get that fixed so it auto updates when new releases come out.
