### ISSUE TITLE
proxmox ve now supports an answerfile. 

### ISSUE THREAD

**Issue by ITJamie** [netbootxyz/netboot.xyz#1454]
**Is your feature request related to a problem? Please describe.**
proxmox ve installer menu currently only supports manual installs

**Describe the solution you'd like**
proxmox ve installer now supports an answerfile. it would be great if the installer was extended to support it

https://pve.proxmox.com/wiki/Automated_Installation#Network_Section

**Comment by kaysond** [comment]
This isn't really practical with Proxmox's current implementation because you need to prepare a custom ISO that tells the installer where to find the answer file. It might be possible for the CI pipeline to be updated to make a generic one with a blind `--fetch-from http`. This would allow users to provide the URL via DNS or DHCP option 251, but there are complications with serving the ISO too. What Proxmox really needs is a kernel option like Debian.

You can set this all up yourself with the existing netboot, though. See https://n1.602176634e-19.pro/006-automated-proxmox-ve-installation-with-netboot.xyz/

**Comment by antonym** [comment]
Agreed, would be ideal to specify it like Debian but when I looked at this, they currently require it to be baked into the iso. Closing this out for now until there's a better method.
