### ISSUE TITLE
Utilities missing from public boot.netboot.xyz

### ISSUE THREAD

**Issue by dlaube** [netbootxyz/netboot.xyz#171]
No sub menu entry for "Utilities" is displayed under "Tools" while booting from the public iPXE location at https://boot.netboot.xyz/. See https://screencast.com/t/3TFVhT3zP

**Comment by antonym** [comment]
Can you provide a few more specifics about the environment you were booting into?  I've started making the menus more dynamic to hide options that won't work on certain architectures.  (https://github.com/antonym/netboot.xyz/blob/master/src/boot.cfg#L28) 

For instance, if using EFI, the utility menu will be hidden as it leverages memdisk which isn't supported under EFI.  The same if using ARM or using Packet as a provider currently.  In most cases, x86_64 should show all options.

**Comment by dlaube** [comment]
Thanks Antony, I think that makes sense. I probably should have mentioned that we're seeing this specifically on the x86_64 architecture over at the Packet.net baremetal hosting provider.

**Comment by antonym** [comment]
Ah, cool, at least the dynamic menus are working then. :) Because most of the utilities are using memdisk to load the ISO of those utilities directly, I'm currently unable to modify the loading kernel lines to adjust for the Packet host console settings, so you probably would not get any output when loading them.  If you'd like to try anyways, you can drop to the iPXE shell and try loading

    chain https://boot.netboot.xyz/utils.ipxe

That should load up the menu so you can experiment with it.  The way around it would be to start extracting the ISOs of all of the utilities and load the kernels directly, but then that basically taints the release of the utility so I haven't quite figured out the best way to handle those cases yet.
