### ISSUE TITLE
Support for Fedora/CentOS/RHEL atomic

### ISSUE THREAD

**Issue by fabaff** [netbootxyz/netboot.xyz#204]
[Atomic Host](http://www.projectatomic.io/) provides an immutable infrastructure to deploy containerized applications.

The installation process is very similar to the existing ones (Fedora/CentOS/RHEL) but they have a different release cycle.

Should "X atomic" be a part of X aka as a product or flavor?

**Comment by antonym** [comment]
I haven't seen much discussion/documentation about the PXE images for Atomic, but it appears that some do exist now whereas previously a lot of Atomic was in flux:

http://mirrors.rit.edu/fedora/alt/atomic/stable/Fedora-Atomic-27-20171211.0/Atomic/x86_64/os/images/pxeboot/

It could be worth trying it.  Is Fedora the only flavor of Atomic currently?  I see some ISOs for CentOS but it doesn't look like they have any PXE images.

**Comment by fabaff** [comment]
I guess that it's only a matter of time till CentOS is shipping more than the ISOs.

What way do you prefer for the menu?

Simple (which is my favorite)

```text
Fedora Atomic
  - Host
  - Workstation
```
Grouping all atomic installation. 

```text
Atomic
  - Fedora
  - CentOS
  - etc.
```
With the next one, I assume that we will run into a more complicated setup than needed as the path will probably not match.

```text
Fedora
  - Workstation
  - Server
  - ...
  - Atomic
``

**Comment by antonym** [comment]
I guess it depends on where the project is going.  Because it's another version of either CentOS/Fedora/RHEL, it probably belongs under those sections.  There doesn't seem to be a ton of differences at this point, at least for Fedora.

I put up a PR (https://github.com/antonym/netboot.xyz/pull/212) for Fedora's version that seems to load things up and it's pretty minimal lines of code to add.  The code would probably be even more simplified if the versions didn't have unpredictable date codes or if they resided under fedora instead of fedora-alt.
