### ISSUE TITLE
Issues booting DBAN/Clonezilla/GPartED

### ISSUE THREAD

**Issue by chris18890** [netbootxyz/netboot.xyz#214]
This weekend I noticed some issues when booting DBAN, when trying to load the ISO from sourceforge I kept getting an error saying “could not boot permission denied http://ipxe.org/022fe23c" I ccould download the ISO normally from a browser, but not from the NetBoot.xyz utilies menu.

I checked other things such as PogoStick & AVG rescue Linux which seemed to work fine, it seemed to be DBAN, Clonezilla & GPartED, all of which are hosted on sourceforge. DBAN was work on Friday intermittently but refused to work on Saturday or Sunday. Not sure if much can be done here or if it’s an upstream issue; I did notice that the Sourceforge URLs were http only, would that make a difference?

**Comment by antonym** [comment]
I wonder if the URLs I'm using are getting redirected and iPXE isn't liking how they are getting redirected.  Are you still having issues with them?

**Comment by chris18890** [comment]
Sorry for the delay, only got around to checking this evening.

They seem to be booting fine now, I tried each one three times -

Clonezilla worked on the 1st & 3rd try but not the second
DBAN worked all 3 tries
GPartED on the 2nd & 3rd tries

I managed to get a photo of the error whenever clonezilla was failing to load, which was a different error code to before

![2018-01-06 23 11 05](https://user-images.githubusercontent.com/3144892/34644922-8567e130-f338-11e7-9743-4a5abe40f139.jpg)

**Comment by barnabyc** [comment]
@antonym Would a redirection url help? Or perhaps a way to specify a base url for these, such as with the Windows installer menu?

**Comment by Firminator** [comment]
The DBAN version on SourceForge is heavily outdated and shouldn't be used. Remember DBAN was bought by a company called Blancco, and code development on open-source DBAN then suddenly halted.
I recommend removing it altogether and using the forked, up to date version located over @ https://github.com/NHellFire/dban/releases which is maintained (although it's a one-man job), stable and working great since several years now. NHellFire added recently Syslinux' vesa32 bootmenu populated with most common wiping scenarios.

**Comment by andrew-stclair** [comment]
i have no idea if this is a related issue, but i am having trouble booting anything from the utilities menu

most things fail with this error
![image](https://user-images.githubusercontent.com/4944499/38023761-daf6b010-32ce-11e8-94b9-16e8e503155c.png)

Memtest86+ just goes back to the main menu

and SystemRescueCD fails with this
![image](https://user-images.githubusercontent.com/4944499/38024279-420997f8-32d0-11e8-9a71-28f078ca505a.png)

i have tested this from both a Hyper-V Virtual Machine (Gen 2) and a HP ENVY 15-bq1xx with identical results

**Comment by andrew-stclair** [comment]
with further testing, the first issue i have discovered has something to do with UEFI

i am now running netboot.xyz.kpxe and Memtestx86+ runs fine

everything else gets Permission Denied (second screenshot above) with exception of Breakin, Partition Wizard, Pogostick and Ultimate Boot CD

it seems everything for sourceforge has the issue

**Comment by seffyroff** [comment]
I am also seeing the permission denied error when trying to boot GParted.  Not sure how to proceed.

**Comment by dol-leodagan** [comment]
The _permission denied_ error seems to be tied to the source being HTTPS instead of HTTP.

The error reported by ipxe ( http://ipxe.org/err/022fe2 ) is related to certificate validation...

**Comment by barnabyc** [comment]
hey @antonym really curious if other folks are having success with the Clonezilla/DBAN/GPartED util menu options at this point? I realized we never resolved this issue. I'm going to try some new ISOs on a custom menu, but wondering if anyone else made progress here.

**Comment by antonym** [comment]
I took a quick look at gparted this morning and I have a feeling iPXE or Sourceforge isn't playing nicely with the /download redirects anymore.  If I try and download the exact URL it's redirecting to, it appears to work.  So it may be a matter of just determining a stable mirror it's redirecting to and updating the URLs.  I haven't had a ton of time to play with this though this week so I welcome anyone else with time to poke around on it and suggest a PR.

**Comment by NiKiZe** [comment]
"Exec format error (http://ipxe.org/2e008081)"
If you get it when booting in efi mode, is most likely due to the fact that you are trying to boot a non efi compliant binary (in the case of linux kernel, it wasn't compiled with CONFIG_EFI_STUB=y)
Which you can read more about on the ipxe,org error page (the url is helpful, and always good to include)

in case of memdisk - that is pcbios only and those items will not work in efi.
also memdisk should be avoided if at all possible.
Memtest86+ is also pcbios only, to run in efi env you need a efi version (which there is few of available for free)

**Comment by antonym** [comment]
Resolved some of the sourceforge builds with:

https://github.com/antonym/netboot.xyz/pull/355

Hopefully that fixes things for the moment.
