### ISSUE TITLE
Solus Linux Request

### ISSUE THREAD

**Issue by o0-o** [netbootxyz/netboot.xyz#215]
Not sure if they have everything you need on their end, but Solus has been getting a lot of positive attention lately. Would be a good addition if possible.

Thanks for all the work on this, I use it all the time.

**Comment by antonym** [comment]
I took a look at Solus a while back and it doesn't appear to play well with Memdisk.  Ideally the project provides network bootable images in the future, but for now I don't think there are any good ways to boot Solus using iPXE without extracting the image and hosting it somewhere.

I'd suggest raising an issue or request a feature with Solus to provide network bootable installer kernels.  Definitely would love to have it added though.

**Comment by antonym** [comment]
Maybe worth revisiting now.

**Comment by thelamer** [comment]
Solus is a hard no for pxe support they even closed source their ISO build stuff because they were afraid of people forking it off and pushing copycat stuff. 
https://dev.getsol.us/T7758
https://discuss.getsol.us/d/1500-how-to-generate-custom-iso

In a world of uncertainty I am near 100% this project will never support network booting unless we write it from scratch, and even then we would likely be fighting with them over it.

**Comment by antonym** [comment]
K, good to know, thanks for digging in.
