### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by 3wille** [netbootxyz/netboot.xyz#22]
As far as I understand iPXE supports HTTPS connections[0]. 
It also seems like you could directly include the root cert of an existing CA like let's encrypt.

[0] http://ipxe.org/crypto

**Comment by oarmstrong** [comment]
Looks like it would be fairly easy to get the final provider images booting from HTTPS, I can take a stab at that tonight.

However, to get the PXE menus loading over HTTPS the certificate needs to be fixed on boot.netboot.zxy.  Is that a CDN somewhere?  It has various names on the certificate like `*.akamaihd.net` referring to Akamai.

Also, is this something you'd want an option for @antonym ?  Or would it be safe to assume that using plain HTTP would never be needed?

**Comment by antonym** [comment]
Yeah, I'd need to switch the main code over to the HTTPS Akamai CDN link and then also switch all items over to pull from HTTPS mirrors.

I'm currently using the default iPXE root CA in iPXE which doesn't appear to support some of the HTTPS sites I'd need to hit.  iPXE currently is pulling the full root ca from http://ca.ipxe.org/ca.crt.  Just need to find some time to wrap my head around it.  Once that's done though, the other changes above are simple.

**Comment by 3wille** [comment]
I think if you use the cert of "normal" root CA it should work with most servers. Normal means accepted by common browsers which implies that most servers will use one of these.
I don't know how difficult it is to change the root ca in iPXE

**Comment by antonym** [comment]
boot.netboot.xyz is now HTTPS enabled and the bootloaders now use it by default.  You'll need to pull down the latest iPXE builds to chain into it by default.  I've left HTTP enabled for now so that users without HTTPS support compiled into iPXE can still chain into netboot.xyz.  

Next I'll probably version out the iPXE loaders next and then have it chain a netboot.xyz image if the versions don't match so that anyone chaining will get a HTTPS supported bootloader.  Then I should be able to redirect HTTP requests to HTTPS.

https://github.com/antonym/netboot.xyz/commit/78cdcec6c51416971b4f8714c38c3ebf872cb625

Still have to work on switching things to HTTPS for the provider images along with checksums.

**Comment by antonym** [comment]
netboot.xyz top domain is now https by default now, closing out.
