### ISSUE TITLE
Using the system on Uni network

### ISSUE THREAD

**Issue by ajcollett** [netbootxyz/netboot.xyz#238]
Hello,

So I really like this project. I have been trying to start a similar project on my University campus, however, I would greatly like to make use of the effort that has already gone in here, and also be able to contribute back instead of simply doing my own thing. 

Problem is, the whole university network is behind a firewall, and no easy way to get around that. 

There are mirrors for many of the distribution on the South African University (TENET) network, so I can make use of those, but what else is there that I would have to replicate locally to get it to work?

I assume I will need to host undi versions if I am to mirror the main repo effectively. 

Any guidance on what access the system usually need to the outside would would be great!

**Comment by antonym** [comment]
Thanks, glad you like it.  I've been slowly working on getting something like that put together so that you can generate your own local netboot.xyz in your environment easily.  I'll try and find some time this week or next to push up what I have so far and maybe that'll be something to iterate on.  

You can modify the boot.cfg today to override the location of a lot of the main OS primary mirrors.  I still need to look into the best way to set utility images as well.  If there's one that you need an override for that isn't there, feel free to open a PR and I can review.

This is open to track this kind of request:

https://github.com/antonym/netboot.xyz/issues/26

**Comment by thelamer** [comment]
closing track #26
