### ISSUE TITLE
CentOS 7 fails to install on Supermicro HW

### ISSUE THREAD

**Issue by xmovu** [netbootxyz/netboot.xyz#248]
Hi guys,

Getting the following error installing CentOS 7, I've no idea why.

![image](https://user-images.githubusercontent.com/2205390/42387018-0ad66f4c-8139-11e8-996b-e84807cfc7cf.png)
![image](https://user-images.githubusercontent.com/2205390/42387028-104a8dfa-8139-11e8-8e22-27090b13bc6b.png)

It's not an isolated event. I've been unable to get netboot.xyz to install CentOS 7 on several E3, Supermicro servers.
Network is configured, not by DHCP but manually.

Any idea?

Cheers

**Comment by antonym** [comment]
Made some changes to see if this can be handled better.  Since you were able to load iPXE to bring up the menu and start the installer, this patch uses that same MAC that got on the network and attempts to reuse it with DHCP.  

https://github.com/antonym/netboot.xyz/commit/b5e0e0f71dd4e16df662b24320182697ffb891d1

If you don't have DHCP we'd probably have to go another route which would be a bit more complex as we'd need to inject the static networking config into the kernel command line as dracut networking configuration.

**Comment by xmovu** [comment]
Hi Anthony!

Thank you for such amazing tool. This is amazing!

To answer your question, there is no DHCP server. Its all manual configured in terms of network. Since I configure the network when it boots initially it should save the configuration, no? Doesnt make much sense in my perspective. I boot netboot, then it tries to configure with DHCP, it fails, I configure the network manually and it downloads some stuff. I then proceed to install CentOS 7 and this happens. IMHO the network config should be saved as it is normally. Weird thing.

**Comment by xmovu** [comment]
Btw I did try to remove the interface from there or rename it like you have done but it wont work either.

**Comment by antonym** [comment]
Yeah, if you set things up manually, it's set within iPXE.  In order for it to pass it to the installer, those values then need to be put on the kernel command line or in most cases, can be set up once inside the installer.  The CentOS installer is a bit tricky as it retrieves a rootfs image during the initrd process where it doesn't really prompted for the IP at that point.  That's why we'd probably need to pass the settings obtained in PXE and funnel them to the kernel.

**Comment by xmovu** [comment]
Anthony,

Interesting. Thats why it fails... Damn. Does make sense now. So basically without DHCP it fails on all sort of hardware.

**Comment by pgera** [comment]
I'm seeing this too (or it looks similar in that it's some networking issue). Tried to boot fedora today. I know that this used to work about a year ago for the same server and same network. Attaching screenshot.
![rpviewer](https://user-images.githubusercontent.com/5542855/42682968-9f4033c6-8651-11e8-96fb-e25874c0833d.png)

**Comment by pgera** [comment]
I saw that the commit was for Centos only. I tested Centos, and I was able to get to the installer. So the fix works. Same would apply to Fedora, RHEL and any others in the family too. Thanks.

**Comment by antonym** [comment]
Cool, good to know, will get that applied on the others too.

**Comment by antonym** [comment]
Added this to Fedora and RHEL.

**Comment by xmovu** [comment]
This is fixed as well with #343 .
