### ISSUE TITLE
AlpineLinux Support

### ISSUE THREAD

**Issue by zQueal** [netbootxyz/netboot.xyz#30]
For anyone who doesn't know, Alpine Linux is tiny. The standard vanilla iso is 81MB with the extended iso a measly 360MB installed.

It would make a really great addition to netboot. They offer a public download repository [here](http://dl-3.alpinelinux.org/alpine/).

**Comment by antonym** [comment]
I gave this a try tonight but unfortunately Alpine Linux ISOs do not play nicely with memdisk which is what I need in order to boot.  You can read more about the issue [here](https://www.reversengineered.com/2016/01/07/booting-linux-isos-with-memdisk-and-ipxe/) and a potential way to fix it.  It might be worth opening the ticket with them and seeing in they are willing to implement the above item.

The way I usually validate an ISO works or not is pulling up the iPXE command shell and running:

kernel http://boot.netboot.xyz/memdisk iso raw
initrd http://URL.to/ISO
boot

If it works, it'll usually start the install or load up all of the way.  If it fails, it'll usually fail early after being unable to load the rootfs image.

The ISOs can be cracked open and hosted somewhere to boot, but that introduces a lot of other issues. (tampering, bandwidth, space, etc).  I'd much rather pull from the provider of the operating system or a trusted mirror if at all possible and leave netboot.xyz as a router to those operating systems.

**Comment by antonym** [comment]
Looks like some others have tried as well, might be a good place to start. http://lists.alpinelinux.org/alpine-devel/3292.html

**Comment by zQueal** [comment]
I've been trying to get some involvement via the Alpine official IRC, but there's been no movement in more than 4 hours despite over 300 connected clients. Not entirely sure this is going to happen. It's far outside my skillset.

**Comment by andyshinn** [comment]
Alpine Linux also has a bug tracker at https://bugs.alpinelinux.org/ and a couple mailing lists I would try as well: http://lists.alpinelinux.org/.

**Comment by zQueal** [comment]
Andy, thanks!

I've opened a thread on their [internal forums](http://forum.alpinelinux.org/forum/installation/netbootxyz-compatability).

**Comment by antonym** [comment]
Thanks, guess we just wait and see.  If we can get a working image, it'll be really easy to get it going.

**Comment by bfritz** [comment]
@zQueal @antonym If I read a recent [IRC chat](http://irclogger.com/.alpine-devel/2016-01-18#1453099968) correctly, @ncopa has some experimental changes to enable pxe boot that might land in Alpine Linux 3.3.2.  They may not be sufficient to pxe boot an ISO though.

**Comment by zQueal** [comment]
@bfritz Hey, that's great news! At least it's a step in the right direction! Thanks for the update.

**Comment by Ttech** [comment]
http://wiki.alpinelinux.org/wiki/PXE_boot is the instructions on how to boot it any reason this wouldn't work?

**Comment by antonym** [comment]
Reopening because I would like to see Alpine support at some point, I may poke around on it if I get some time.

**Comment by IxDay** [comment]
Ok managed to found a solution to create a bootable image for alpine through IPXE, here are the steps:

- clone the [alpine-iso git repo](http://git.alpinelinux.org/cgit/alpine-iso/)
- cd to the directory and create the following two files: 
  - `alpine-pxe.packages` which will be empty (those packages are installed in the iso not in the initrd)
  - `alpine-pxe.conf.mk` with the following content:
    ```
    ALPINE_NAME   := alpine-pxe
    KERNEL_FLAVOR := grsec
    INITFS_FEATURES := ata base bootchart squashfs ext4 usb virtio network dhcp
    MODLOOP_EXTRA :=
    ```
    some options may not be needed, I did not had the time to check this correctly, `virtio` and `network` are needed according to [the wiki](https://wiki.alpinelinux.org/wiki/PXE_boot#Using_pxelinux_instead_of_gPXE)
- create the image following the instructions [here](https://wiki.alpinelinux.org/wiki/How_to_make_a_custom_ISO_image) and pass your new profile: `make PROFILE=alpine-pxe`
- start a simple http server in `isotmp.alpine-pxe/isofs/boot/` the ipxe boot will need the two following files:
  - `initramfs-grsec`
  - `vmlinuz-grsec`
- create your ipxe script with an adaptation of the following to your own url
  ```
  #!ipxe

  dhcp

  set base-url http://192.168.122.0:5050
  set kernel-params ip=dhcp modules=loop,squashfs,usb-storage nomodeset

  kernel ${base-url}/vmlinuz-grsec ${kernel-params}
  initrd ${base-url}/initramfs-grsec

  boot
  ```
  Here again I am not sure that all the options are needed, still have to perform some tests.
- start your network boot!

**Comment by Ttech** [comment]
I'd love to see this added in as well since Alpine is such a easy to use lightweight distro.

**Comment by jjzazuet** [comment]
Hi. Chiming in to see if Alpine is now offering kernel+initrd bundles, or if we still need to follow @IxDay 's instructions. Thanks!

**Comment by antonym** [comment]
I hadn't heard any updates, but I'd still be all for it if Alpine Linux would provide a hosted version of those files so they could be retrieved.  I could spin and host them myself, but generally would prefer if the provider provided the files uncompressed on their mirror so that they could be loaded by anyone directly as it's generally more trustworthy.  I'd also like to start getting away from ISOs where possible as the methods to load them in iPXE just aren't ideal.  If anyone knows any Alpine Linux maintainers, please ping them to this thread.

**Comment by Red5d** [comment]
There's now a PXE booting guide for Alpine which mentions using gpxe scripts and booting over HTTP: https://wiki.alpinelinux.org/wiki/PXE_boot

**Comment by antonym** [comment]
Yeah, the issue of adding support isn't about how to do it but we need to have the files hosted as part of the release so the ISO doesn't have to be extracted and hosted at another source.  It would be ideal if the files that worked for PXE support would be hosted by the projects directly so that they could be pulled from the primary and trusted source.  

If those are present somewhere already on an official Alpine Linux mirror, please point me to them and I can get support added.

**Comment by dunielpls** [comment]
I run mirrors and I am on Alpine's infrastructure team. I will get back to you shortly @antonym

**Comment by antonym** [comment]
Merged in some experimental Alpine Linux support, hopefully we can get an official build at some point but this should be a good starting point to play around with and use.

**Comment by nekocentral** [comment]
As of today Alpine linux 3.8 has a official Netboot image, do you think it can be implemented as the main alpine image?

**Comment by antonym** [comment]
That's great news but unfortunately, their release is tar.gz up so it's not something iPXE can pull directly from their servers and use.  Do they have the releases extracted somewhere and hosted on their official servers?  I don't typically host the bits myself and rely on the distribution to provide a place to retrieve from their official mirrors.

**Comment by nekocentral** [comment]
I know that a mate of he hosts a mirror of alpine, i can ask him if he can do an extracted folder of the tar

**Comment by antonym** [comment]
The expermental images are currently hosted by one of the developers but I'd like to see if the project would be willing to provide those images extracted for use by anyone in official capacity without having to download the tarball directly.

**Comment by nekocentral** [comment]
Looks like an extracted package is live on the actaul CDN's
http://dl-cdn.alpinelinux.org/alpine/v3.8/releases/x86_64/netboot/

**Comment by antonym** [comment]
Perfect, we can use that then, thanks for the heads up!

**Comment by nekocentral** [comment]
No problem

**Comment by antonym** [comment]
Alpine Linux updated to netboot images, dropped experimental tag and added signature checking:

https://github.com/antonym/netboot.xyz/pull/246

Please kick the tires and thanks everyone for getting us this far!
