### ISSUE TITLE
Manjaro 18.0.4 - out of memory

### ISSUE THREAD

**Issue by jamincollins** [netbootxyz/netboot.xyz#335]
Attempting to boot the Manjaro 18.0.4 ISO results in an **out of memory** error after the initial Manjaro boot menu.

The virtual machine this was tested on is configured for 16G of RAM.  So, I don't believe this is a limitation of the system being boot, but rather an error/issue with either iPXE or the configuration.

**Comment by antonym** [comment]
The iso appears to be over 2GB and memdisk I believe starts having issues with files that large in size because it's loading the ISO into the 32-bit address space which starts getting tight on space.  We'd probably need them to either provide a smaller minimal ISO or extract and host a version that has the kernels and rootfs extracted out so we could more properly boot the ISO.  Using memdisk and a giant ISO, unfortunately, isn't very scalable for this kind of tool.

**Comment by jamincollins** [comment]
Agreed, but figured you would want to know that the menu entry you're hosting/offering is currently broken.

**Comment by antonym** [comment]
Thanks for the heads up... may have to look into removing it.

**Comment by jamincollins** [comment]
It can be booted through loop mounting similar to how Arch Linux is booted.  If you'd like I can post my config or create a PR based on my config when I'm finished with it.
