### ISSUE TITLE
remove old ubuntu distros

### ISSUE THREAD

**Issue by chris18890** [netbootxyz/netboot.xyz#54]
Ubuntu 15.04 Vivid Vervet 
Ubuntu 14.10 Utopic Unicorn
Ubuntu 13.10 Saucy Salamander
Ubuntu 12.10 Quantal Quetzal

These should be removed from /src/ubuntu.pxe as they're no longer supported (looks like 13.04 has either been already removed or never present)

**Comment by kjmancuso** [comment]
-1

There is value keeping historical releases even though they are EOL via netboot. For example, there are times where I would like to replicate a legacy environment for testing which is an ideal usecase for using a tool like netboot for rapid-er deployments instead of keeping archived ISOs lounging around.

**Comment by antonym** [comment]
![img](https://ak-hdl.buzzfed.com/static/2015-03/26/19/enhanced/webdr06/enhanced-25942-1427414324-7.jpg)

https://github.com/antonym/netboot.xyz/pull/55

**Comment by chris18890** [comment]
:+1: :)
