### ISSUE TITLE
Add Gentoo

### ISSUE THREAD

**Issue by timjp87** [netbootxyz/netboot.xyz#57]
It's more well known than most of the niche distros that are currently supported and has nice minimal live install images.

https://www.gentoo.org/downloads/

**Comment by antonym** [comment]
Yeah, I've gotten Gentoo working in the past but unfortunately it involves myself hacking up the images and hosting them myself.  

https://wiki.gentoo.org/wiki/Installation_alternatives

I'd much rather see official support from Gentoo for network booting, [memdisk ISO support](http://netboot.xyz/faq/#will-my-favorite-distribution-work), or at least hosting the modifed/working images themselves.

This was my previous commit that I've pulled since it needs to be redone the right way.

https://github.com/antonym/netboot.xyz/commit/1d8983d327f01ef0fa74a2df09e8604151792d0d

**Comment by antonym** [comment]
Added: https://github.com/antonym/netboot.xyz/pull/107
