### ISSUE TITLE
Elementary OS support

### ISSUE THREAD

**Issue by marcosfede** [netbootxyz/netboot.xyz#67]
thanks for netboot! it's awesome. Is it possible to include elementaryOS in it?

**Comment by antonym** [comment]
I don't think it has support needed for me memdisk support as I think I tried it several weeks back.  See this: http://netboot.xyz/faq/#will-my-favorite-distribution-work

It should be possible to add, we'd just need to raise an issue with the distro to have them add support.

**Comment by davidak** [comment]
i'm not sure if elementary would appreciate this way of distribution of their OS since users should consider paying for it.

@danrabbit

**Comment by antonym** [comment]
Looks like the website allows you to enter in a $0 dollar amount for "Download" instead of purchase, so I don't see why this would be an issue.  Anyone who wants to support the project should be able to donate at will.

If the OS required a license key and didn't have the $0 option, then I'd probably close the issue.  netboot.xyz is about making it easier for anyone to install their Linux operating system of choice.

I'd love to work with the creators on getting iPXE/netboot support possible for ElementaryOS if they are willing.

**Comment by davidak** [comment]
@antonym it is totally fine that users decide to pay $0, there is no license key.

i created an issue upstream: https://bugs.launchpad.net/elementaryos/+bug/1661290

**Comment by antonym** [comment]
Elementary OS added as a Live Boot option, closing this out: https://github.com/netbootxyz/ubuntu-squash/tree/elementaryos-5
