### ISSUE TITLE
Windows installers?

### ISSUE THREAD

**Issue by JakeHedman** [netbootxyz/netboot.xyz#76]
How does one enable the windows installer option which is seen in the animation in README.md and in menu.ipxe?

**Comment by chris18890** [comment]
I believe the animation is from an older version when windows installers were included, but I believe as of commit 8045d4535a7c6d164db8612c97546a2fc79ae989 they were removed, I've no idea if @antonym will bring them back or not!

**Comment by chris18890** [comment]
Also FWIW I've not been able to get them to work with iPXE< but booting WinPE ISOs via Memdisk on my own legacy pxe setup has worked grand

**Comment by antonym** [comment]
Yeah, I removed the Windows PE image because the place they are hosted from needs to be trusted and also they eat up a lot of bandwidth.  I'm also not sure of the licensing issues with Microsoft.  If anyone is more knowledgable or knows anyone at Microsoft willing to work with this concept, please send them my way.  I'd love to have all of the available installers available on the menu if Microsoft provided an easy way to utilize the hosted images.

I thought about setting up the Windows wimboot loaders and then letting people self host their WIMs which would mean specifying having to manually enter in their self hosted URL but I'm not sure how valuable that would be.

I did put together hooks that let you create your own menu by forking the custom repo which may be another option for the moment:

https://github.com/antonym/netboot.xyz/pull/62

**Comment by spillevink** [comment]
@antonym: Could checksums be used to handle the trust problem?

**Comment by JakeHedman** [comment]
Could hosting the images on github solve the bandwidth and trust issues? If not I could hook you up with a digitalocean VPS with unlimited bandwidth and checksums could be used to handle the trust issues.

I tried to find the winPE license online but didn't really find anything more than people talking about it, like the [warning section](https://wiki.archlinux.org/index.php/Windows_PE) on the arch wiki for example.

I was unable to find anything about legal contact on their website. Maybe customer support can answer questions about licensing stuff, I didn't find an appropriate section on the "contact us" page.

**Comment by Ttech** [comment]
Could we have the option to host these locally? Along with ESXI and other software this would make deployments easier. I have a WDS setup similar to this, but using pxelinux and not automated. Be happy to try to test anything to make it work with this.

**Comment by TyrfingMjolnir** [comment]
I have quite a few images I would like to run locally, as those images are quite big, such as debian full, SmartOS, MacOS X 10.9, 10.10, and 10.11, I also would not mind having architect run locally. After all local speed is 0.2ms, and speed for the public images is like 20ms +

**Comment by antonym** [comment]
Supported initial added for Windows Installers, requires you to set up the location an extracted iso: 

https://github.com/antonym/netboot.xyz/pull/105
