### ISSUE TITLE
netboot.xyz-efi.iso triggers windows defender [Trojan:Script/Conteban.A!ml] malware detection.

### ISSUE THREAD

**Issue by gtxaspec** [netbootxyz/netboot.xyz#781]
https://boot.netboot.xyz/ipxe/netboot.xyz-efi.iso 

downloading this iso on windows 10, with windows defender enabled, triggers deletion due to Defender flagging it containing a trojan:  Trojan:Script/Conteban.A!ml [Threat Blocked]

**Comment by antonym** [comment]
Was unable to reproduce on Windows 10, Defender's latest build did not identify any issues with the ISO.

**Comment by dadatuputi** [comment]
I just experienced this same issue, latest Windows 10 and latest ISO from git README.

**Comment by gtxaspec** [comment]
@antonym Just tried this again, like @dadatuputi did, and yes, it failed again, the same virus "detected"

Windows Defender Info:
`Version: 1.341.677.0
Engine Version: 1.1.18200.4
Platform Version: 4.18.2105.5
Released: 6/13/2021 8:39:16 PM`

**Comment by antonym** [comment]
I ran across this too this time when trying to download it as well.  The last modified date was April 25th when it was uploaded from the CI for the 2.0.37 build, these images actually aren't used anymore since I switched to a combined hybrid legacy and efi ISO which is also using a different build method to generate the ISO.  Downloading the hybrid ISO didn't trigger anything with defender (https://boot.netboot.xyz/ipxe/netboot.xyz.iso).

I'll clean out those old images since they aren't used or built anymore, more than likely it's just a false positive.
