### ISSUE TITLE
Unable to load Custom Menus from GitHub

### ISSUE THREAD

**Issue by BasicWombat** [netbootxyz/netboot.xyz#785]
**Describe the bug**
When loading custom menu from GitHub, I get the error "Operation not permitted (http://ipxe.org/410de185f)"

**Additional context**
It appears to be an issue with TLS and accessing the HTTPS of GitHub.
Tested on different computers and same result.

**Comment by BasicWombat** [comment]
Could be related to the same issue:
#782 https://github.com/netbootxyz/netboot.xyz/issues/782

**Comment by BasicWombat** [comment]
@antonym has been helping on this issue via the Discord chat

**Comment by LordChunk** [comment]
@BasicWombat did you find a fix/workaround?

**Comment by BasicWombat** [comment]
> @BasicWombat did you find a fix/workaround?

Unfortunately no. While I did work on it further that day, I wasn't able to find anything.
I also haven't had a opportunity since.

For reference, this a link to the discord conversation with @antonym.
https://discord.com/channels/425186187368595466/425186187368595468/784165591236739082

**Comment by Firminator** [comment]
I can't load my custom menu either anymore. Though the error code is 410de13c (aka 410de1 @ https://ipxe.org/err/410de1 )

**Comment by Firminator** [comment]
Wild speculation here.
boot.netboot.xyz uses an Amazon cert.
raw.githubusercontent uses DigiCert[1].
Could it be that the DigiCert RootCA is not added to the netboot image hence TLS requests to raw.githubusercontent/username/netboot.xyz-custom/master/custom.ipxe will fail?
Anthony suggested to generate certificates and manually them add before building custom netboot images @ https://github.com/netbootxyz/netboot.xyz/issues/237 although we are not building custom images here. We are just using our own repo on Github/raw.githubusercontent.com instead of boot.netboot.xyz

[1] https://www.ssllabs.com/ssltest/analyze.html?d=raw.githubusercontent.com

**Comment by antonym** [comment]
I did some debug the other day and was getting back the 02 28 error that it mentions on iPXE:

```
If server replies with “02 28”, then TLS was unable to negotiate compatible
cipher suites between iPXE and your server.  Enable something on the server
side to show what is supported by iPXE.
```

It was working up until a few weeks ago, so I suspect Github changed something service side on raw.githubusercontent.com that isn't jiving with what iPXE is compatible with.  I haven't had much time to dig into this, but we do leverage the ipxe ca with a netboot.xyz code signing cert for signature checking.

I have thought about adding an additional option for loading up menu configs from a URL so that portion of it isn't so dependent on GitHub usernames or their endpoint.  Then you can just load the custom menu from anywhere and have more control over compatibility.

**Comment by barnabyc** [comment]
I just moments ago was trying to set github_user via local-vars.ipxe for the first time and thought I had broken something when getting "Operation not permitted", glad it wasn't just me!

A way to override the custom menu base url via local-vars.ipxe could be really useful. In fact, using local-vars.ipxe to override any particular url would be awesome (eg. in the case of locally-hosted Debian mirrors, etc)

**Comment by LordChunk** [comment]
Disabling IPv6 on my network seems to resolve the issue.

**Comment by hipposen** [comment]
a bit off-topic but without ipv6 the image download from github is successful

**Comment by Firminator** [comment]
> Disabling IPv6 on my network seems to resolve the issue.

Disable IPv6 where? Switch, Firewall, DHCP-server?

> a bit off-topic but without ipv6 the image download from github is successful

Which image?

**Comment by bjo81** [comment]
I didn't try it without IPv6 yet, but I'm wondering why IPv6 is an issue as it worked already on an IPv6-enabled network. And `raw.githubusercontent.com` does not have IPv6.
```

raw.githubusercontent.com is an alias for github.map.fastly.net.
github.map.fastly.net has address 151.101.112.133

```

**Comment by barnabyc** [comment]
This seems to be working once again. Was testing a few hours ago. I had not changed any IPv6 settings. Maybe GitHub adjusted their access rules?

**Comment by antonym** [comment]
Yeah, it's working for me now again too.

**Comment by antonym** [comment]
This appears to still be working so closing this out.  I've also added the ability to set a custom url in case functionality with github breaks again.
