### ISSUE TITLE
Error installing any debian version.

### ISSUE THREAD

**Issue by KeizerDev** [netbootxyz/netboot.xyz#81]
My VM shows me this:
![screenshot from 2016-02-15 16-11-11](https://cloud.githubusercontent.com/assets/4026917/13052364/c5a5218c-d3fe-11e5-90ae-c3064fd8cdfa.png)

**Comment by antonym** [comment]
Thanks for opening a bug for this, it should be fixed now.  I started signing all of the installer kernels this weekend for signature verification on the remote images.  I pushed them out last night but I missed the gtk (Graphical) kernels since their directory structures don't align correctly.  The text based versions were working at least.  

They are signed now and deployed so let me know if you run into any more issues or anymore that I might have missed.
