### ISSUE TITLE
netboot gets stuck on "iPXE initialising devices"

### ISSUE THREAD

**Issue by kaysond** [netbootxyz/netboot.xyz#839]
**Describe the bug**
net-booting my R720XD gets stuck on`iPXE initialising devices`

**To Reproduce**
1. network boot on an R720XD with Broadcom 57800 10G/GbE 2+2P nic

**Expected behavior**
netboot loads

**Additional context**
My netboot setup works totally fine on my VM's, but those are using virtual intel nics. I suspect its some issue with broadcom drivers, but not sure how to further debug

**Comment by antonym** [comment]
Have you tried the the undionly or snponly images?  I would also check upstream with the iPXE project to see if anyone else has had difficulties with those NICs.

**Comment by kaysond** [comment]
So I tried the snponly, and it booted and gave me some errors:
https://ipxe.org/err/040ee1
https://ipxe.org/err/2a0860

I think the problem might be related to my vlan settings as it gives me this error when I try to manually set up the vlan: https://ipxe.org/err/7f11e094

![image](https://user-images.githubusercontent.com/1147328/106854201-c1936f00-666f-11eb-898b-90eb634bb2c4.png)

**Comment by Firminator** [comment]
The BCM578xx on earlier FW[**1**] had issues w/ intermittent PXE boot failures. What firmware is this NIC running? The latest is 15.x.x but not because they were major new features warranting a new major version, but rather because vendors/FW developers changed like 3 times for this chip (Broadcom->Marvell->Qlogic->Cavium with no guarantee that this is the right order).  

[**1**] the 7.12.x train specifically

**Comment by kaysond** [comment]
> vendors/FW developers changed like 3 times for this chip (Broadcom->Marvell->Qlogic->Cavium
I was wondering what the heck was going on with that. 

I'm running FW 15.15.08

**Comment by kaysond** [comment]
Seems like this is definitely an upstream issue related to vlans: https://github.com/ipxe/ipxe/discussions/248

**Comment by Firminator** [comment]
Awesome. You're on to something there. I'm sure they can figure this out. Because this card was in the default NIC selection list when buying 12G DELL servers the fix will benefit a lot of folks in corporate environments NETBOOT.XYZing... well, unless they still run a flat network.

**Comment by kaysond** [comment]
> Awesome. You're on to something there. I'm sure they can figure this out. Because this card was in the default NIC selection list when buying 12G DELL servers the fix will benefit a lot of folks in corporate environments NETBOOT.XYZing... well, unless they still run a flat network.

Yeah I'm kinda shocked no one has run into this before...

**Comment by tombull89** [comment]
I have the same issue, I get stuck on `iPXE initialising devices` when trying to boot my machine. This is a Generation 1 VM running on Hyper-V on Windows 10 Pro x64 20H2. Happens if I boot from the disk image, or pxe boot the DHCP-undionly/DHCP versions. I don't have any VLANs, and the image works fine on my ESXi VMs if I test boot them. I suspect it's due to the driver of the Hyper-V VM but unlike ESXi VMs there's only one network card type avalible, a virtual Intel one.

**Comment by kaysond** [comment]
Issue filed upstream
