### ISSUE TITLE
The mouse and keyboard doesn't work with Debian live

### ISSUE THREAD

**Issue by vstavrinov** [netbootxyz/netboot.xyz#845]
I have tried most of the available desktops - every boot successfully but the mouse pointer sticks on the screen without movement for all of them.  Similar true about the keyboard - there are no any reactions on any keypress. Both virtual and hardware machines were tested with the same result.

**Comment by antonym** [comment]
Looks like the kernel being used was older than the release as it missed getting transitioned from Travis CI.  Once I got the kernel aligned, the mouse and keyboard seem to work, so working on getting that all fixed up.  Will update once it's released.

**Comment by antonym** [comment]
Appears to be working on the development endpoint, fixes should go out in 2.0.34 release.

**Comment by putnam** [comment]
This might be broken again as far as I can tell. 

The first thing I tried, the "Debian Core" image, is missing things like ext/2/3/4 support. I was trying to use it to rescue a system and at this point I am not sure which if any of the Debian images in netboot.xyz are functional. Also, my keyboard was barely usable (very sluggish and dropping random inputs). I had to patiently and carefully get ssh up before I could look around at all.

The second thing I tried was the Gnome image. After boot I get a frozen desktop with a partially-rendered "Welcome" dialog and the mouse and keyboard don't work.

The last thing I tried was the Bullseye KDE image. After it began booting and the framebuffer came up, the systemd job for "Load Kernel Modules" failed, then the kernel output made it to "Started Simple Desktop Display Manager" and nothing happened after that.

Based on the discussion above, it sure sounds like whatever builds the base image is missing a lot of kernel modules again.

Since I'm here, I might also point out the net installer for Debian Testing has been broken for the better part of a decade. It probably shouldn't be in the menu. It might work during the time when testing is actually the beta for the upcoming release but the installer usually stays broken for years at a time.

**Comment by ed-at-protectli** [comment]
Perhaps another vote to reopen/revisit this. Our testing shows that Debian Live (Core) works just fine, but none of the flavors that include a DE seem to detect a keyboard.

By adjusting the boot parameters to enable serial console, and then installing openssh-server, we were able to dig a little further and see that xinput does not recognize any devices.

```
user@debian:~$ DISPLAY=:0 xinput
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
```

Additionally, `/var/log/Xorg.0.log` seems to not have any evidence of detecting the devices:

```
X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
[   288.331] Build Operating System: linux Debian
[   288.331] Current Operating System: Linux debian 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64
[   288.331] Kernel command line: vmlinuz boot=live fetch=https://github.com/netbootxyz/debian-squash/releases/download/11.5.0-c360bf0e/filesystem.squashfs initrd=initrd.magic vg
a=normal console=tty0 console=ttyS0,115200n8
[   288.331] Build Date: 05 August 2022  08:00:36AM
[   288.331] xorg-server 2:1.20.11-1+deb11u2 (https://www.debian.org/support) 
[   288.331] Current version of pixman: 0.40.0
[   288.331]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[   288.331] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   288.331] (==) Log file: "/var/log/Xorg.0.log", Time: Thu Dec 15 22:09:24 2022
[   288.335] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   288.338] (==) No Layout section.  Using the first Screen section.
[   288.338] (==) No screen section available. Using defaults.
[   288.338] (**) |-->Screen "Default Screen Section" (0)
[   288.338] (**) |   |-->Monitor "<default monitor>"
[   288.338] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[   288.338] (==) Automatically adding devices
[   288.338] (==) Automatically enabling devices
[   288.338] (==) Automatically adding GPU devices
[   288.338] (==) Max clients allowed: 256, resource mask: 0x1fffff
[   288.341] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   288.341]    Entry deleted from font path.
[   288.345] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        /usr/share/fonts/X11/100dpi/:unscaled,
        /usr/share/fonts/X11/75dpi/:unscaled,
        /usr/share/fonts/X11/Type1,
        /usr/share/fonts/X11/100dpi,
        /usr/share/fonts/X11/75dpi,
        built-ins
[   288.345] (==) ModulePath set to "/usr/lib/xorg/modules"
[   288.345] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[   288.345] (II) Loader magic: 0x55c57b1cbe40
[   288.345] (II) Module ABI versions:
[   288.345]    X.Org ANSI C Emulation: 0.4
[   288.345]    X.Org Video Driver: 24.1
[   288.345]    X.Org XInput driver : 24.1
[   288.345]    X.Org Server Extension : 10.0
[   288.345] (++) using VT number 7
```

The keyboard is, however, detected by `lsusb` 

```
user@debian:~$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 046a:0023 Cherry GmbH Keyboard
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Passing other X devices from my remote session (using `ssh -X`) exhibits better behavior, but still no interaction with the DE. Namely, these devices appear in `xinput`, but not in `DISPLAY=:0 xinput`.
