### ISSUE TITLE
How can I add a local image to this kind of setup?

### ISSUE THREAD

**Issue by TyrfingMjolnir** [netbootxyz/netboot.xyz#94]
How can I add a local image to this kind of setup?

Let's say I would like to run UBCD from a local repo while I run the other stuff fresh from the world wide wait.

**Comment by antonym** [comment]
See https://github.com/antonym/netboot.xyz/pull/62

It lets you put your github user name in and it'll generate your own custom menu based on a fork of https://github.com/antonym/netboot.xyz-custom

You could even regenerate the iPXE disks and set your github user as a variable in order to skip having to set the name every time.

It's still experimental so would love to get some feedback/testing on it.

**Comment by TyrfingMjolnir** [comment]
This will allow me to clone from github or require me to be addicted to github?

**Comment by chadmiller** [comment]
This software uses Github. You've used it before.

**Comment by TyrfingMjolnir** [comment]
Of course, but I would really like to deploy on-prem.

**Comment by webairnetboot** [comment]
This seems like a duplicate of [Self-hosting Instructions #26](https://github.com/antonym/netboot.xyz/issues/26 )
